- src/aind_mri_utils/optimization.py
- tests/test_file_io_simpleitk.py
- tests/test_optimization.py
Clean up optimization code by moving the constant out of the function logic
> Move headframe hole locations to constant

- src/aind_mri_utils/file_io/slicer_files.py
- src/aind_mri_utils/headframe_rotation.py
- src/aind_mri_utils/optimization.py
- tests/test_optimization.py
This is a high-level function that accepts MRI image, segmentation image, and plane points, and calculates the transform required to align the MRI to the headframe coordinate system.
> Add high-level function to calculate the headframe rotation from image files

- .github/workflows/tag_and_publish.yml
- .github/workflows/test_and_lint.yml
- README.md
> Update gh action workflows

- src/aind_mri_utils/planning.py
Also allow considered_ndxs to be None in find_other_compatible_insertions
> Disallow duplicate insertions

- src/aind_mri_utils/file_io/neuroglancer.py
Starting code for neuroglancer io
> Added io for neuroglancer jsons

- src/aind_mri_utils/file_io/neuroglancer.py
> Updated typo

- src/aind_mri_utils/file_io/neuroglancer.py
> Run linters

- src/aind_mri_utils/headframe_rotation.py
Allow for using only some of the headframe segments when calculating centers of mass and headframe rotations.
> Add ignore list to headframe rotation functions

- src/aind_mri_utils/file_io/neuroglancer.py
> Delete trailing whitespace

- src/aind_mri_utils/file_io/slicer_files.py
> Refactor read_slicer_fcsv to eliminate flake8 errors

- src/aind_mri_utils/file_io/image_files.py
- src/aind_mri_utils/file_io/slicer_files.py
- src/aind_mri_utils/headframe_rotation.py
- src/aind_mri_utils/measurement.py
- src/aind_mri_utils/meshes.py
- src/aind_mri_utils/optimization.py
- src/aind_mri_utils/planning.py
- src/aind_mri_utils/plots.py
- src/aind_mri_utils/reticle_calibrations.py
- src/aind_mri_utils/rotations.py
- src/aind_mri_utils/sitk_volume.py
- tests/test_optimization.py
- tests/test_rotations.py
> Spellcheck

- src/aind_mri_utils/file_io/simpleitk.py
Adding documentation to explain the interface of `save_sitk_transform`
> Expand documentation of save_sitk_transform

- src/aind_mri_utils/headframe_rotation.py
- src/aind_mri_utils/implant.py
- src/aind_mri_utils/optimization.py
Also rotate the implant, not the mesh when finding implant fit
> Return unpacked values instead of parameter vectors used for optimization

- src/aind_mri_utils/file_io/neuroglancer.py
- src/aind_mri_utils/optimization.py
Arguments not splatted when making homogeneous transform during optimization
> Fix failing CI  tests

- src/aind_mri_utils/arc_angles.py
- src/aind_mri_utils/rotations.py
The old ones weren't working for me
> Change arc angle calculations

- src/aind_mri_utils/file_io/slicer_files.py
- src/aind_mri_utils/optimization.py
- src/aind_mri_utils/reticle_calibrations.py
- src/aind_mri_utils/rotations.py
- tests/test_reticle_calibrations.py
The scaling parameter is included for informational purposes only
> Instead of returning a rotation matrix, return an affine matrix

- .gitignore
- src/aind_mri_utils/reticle_calibrations.py
- tests/test_reticle_calibrations.py
Combine multiple calibrations for one experiment
> Combine calibrations

- pyproject.toml
- src/aind_mri_utils/file_io/masks.py
Added some mostly Chat-GPT code that allows for reading masks directly from .nrrd files into trimesh meshs. Eliminates the need to use Slicer for conversion
> Read masks

- src/aind_mri_utils/implant.py
Often we are only interested in the mean position, which we can call on each segmentation as it is found.
> feat: Add a function to call on implant segmentations

- src/aind_mri_utils/implant.py
Function accepts SimpleITK.Image, not numpy.ndarray
> fix[documentation]: make_hole_seg_dict had wrong type information

- src/aind_mri_utils/reticle_calibrations.py
add keyword parameters to enable separate specification
> feat: Allow specification of find_scaling for pallax and manual calibration

- src/aind_mri_utils/reticle_calibrations.py
> More verbose calibration debug statements

- src/aind_mri_utils/meshes.py
> fix: load Newscale models without mirroring them

- src/aind_mri_utils/__init__.py
- src/aind_mri_utils/coordinate_systems.py
- src/aind_mri_utils/file_io/slicer_files.py
- src/aind_mri_utils/headframe_rotation.py
- src/aind_mri_utils/implant.py
- src/aind_mri_utils/meshes.py
Code had incomplete support for missing segments during calculation of headframe rotation.
> fix: allow for headframe segment to be missing

- .github/workflows/tag_and_publish.yml
- .github/workflows/test_and_lint.yml
- pyproject.toml
Modernize python versions used to test package
> modernize test matrix range

- .github/workflows/bump-version.yml
- .github/workflows/ci.yml
concurrency issues, gating bump
> chore: update CI

- .github/workflows/ci-call.yml
- scripts/run_linters_and_checks.sh
Name package correctly, make convenience script for linting
> chore: tweak ci
